OAuth connect in popup window sample
transferwise/wise-platform-samples pull request #3
Opened 2023-10-11 07:57 UTC by taaviaasver

## Context

Adding sample code of how to implement authorization flow in a popup window.

In regular authorization flow your application redirects the customer to the Wise authorization page. With some additional steps it can be implemented inside a popup window, meaning that the user does not leave your app.

Ticket: https://transferwise.atlassian.net/browse/DEVEX-45

## Checklist
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

2023-10-11 12:35 UTC, flakron-vranovci requested changes

2023-10-11 12:35 UTC, flakron-vranovci commented on oauth-connect-popup/README.md
> +On high level you'll only need to do two changes:
On **a** high level..

2023-10-11 12:35 UTC, flakron-vranovci commented on oauth-connect-popup/README.md
> +- open Wise authorization page in a popup window instead of a full redirect
open **the** Wise...

2023-10-12 12:25 UTC, taaviaasver commented on oauth-connect-popup/README.md
> +- open Wise authorization page in a popup window instead of a full redirect
Thanks!

2023-10-16 08:53 UTC, flakron-vranovci approved these changes

2023-10-16 08:59 UTC, merged